name: Auto Sync Osteoporosis Branch

on:
  schedule:
    - cron: '*/15 * * * *'   # every 15 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          fetch-depth: 0

      - name: Add source repository
        run: |
          git remote add source https://github.com/isumenuka/osteoporosis-risk-prediction.git
          git fetch source

      - name: Force sync Osteoporosis branch
        run: |
          git checkout Osteoporosis
          git reset --hard source/main

      - name: Push updates
        run: |
          git push origin Osteoporosis --force
